
#微服务配置
spring:
  application:
    name: system-service #服务名  配置文件拼接： 服务名+环境名+后缀 content-api-dev.yaml
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.101.65:3306/xcplus_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
      username: root
      password: mysql
  cloud:
    nacos:
      server-addr: 192.168.101.65:8848
      config: #配置文件相关信息
        namespace: dev_yfr
        group: xuecheng_repository_1022-day6
        file-extension: yaml
        refresh-enabled: true
  profiles:
    active: dev   #环境名