### 上传文件
POST http://localhost:63010/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="33.jpg"
Content-Type: application/octet-stream

< d:/1.jpg
